import assert from 'node:assert/strict';
import test from 'node:test';
import { extractRequirements, generateTraceabilityMarkdown, parseChangeYamlText } from './document-governance-lib.mjs';

test('extracts Requirement-owned test IDs', () => {
  const requirements = extractRequirements('### REQ-ONE-001 One\n\nAcceptance: `AT-ONE-001` and `CT-ONE-001`.\n\n### NFR-TWO-001 Two\n\nAcceptance: `CT-TWO-001`.\n');
  assert.deepEqual(requirements, [
    { id: 'REQ-ONE-001', tests: ['AT-ONE-001', 'CT-ONE-001'] },
    { id: 'NFR-TWO-001', tests: ['CT-TWO-001'] },
  ]);
});

test('generates deterministic active and completed Work indexes', () => {
  const text = '### REQ-ONE-001 One\n\nAcceptance: `AT-ONE-001`.\n';
  const changes = [
    { change: { id: 'CHG-2026-001-old', status: 'Verified', requirements: ['REQ-ONE-001'], adrs: ['ADR-0001'] } },
    { change: { schema: '2', id: 'CHG-2026-002-new', status: 'Active', requirements: ['REQ-ONE-001'], adrs: ['ADR-0002'] } },
  ];
  const output = generateTraceabilityMarkdown({ requirementText: text, changes, archivedIds: new Set(['CHG-2026-001-old']) });
  assert.match(output, /Generated by `pnpm docs:trace`/);
  assert.match(output, /CHG-2026-002-new.*Active/);
  assert.match(output, /CHG-2026-001-old/);
  assert.equal(output, generateTraceabilityMarkdown({ requirementText: text, changes, archivedIds: new Set(['CHG-2026-001-old']) }));
});

test('parses minimal schema-v2 metadata', () => {
  const change = parseChangeYamlText('schema: "2"\nstatus: "Draft"\ngoal: "Preserve a decision"\nrequirements: []\n');
  assert.equal(change.schema, '2');
  assert.equal(change.status, 'Draft');
});

test('preserves compound LAN Requirement IDs', () => {
  assert.deepEqual(extractRequirements('### REQ-LAN-SYNC-001 Sync\nAcceptance: `CT-LAN-SYNC-001`.\n'), [{id:'REQ-LAN-SYNC-001',tests:['CT-LAN-SYNC-001']}]);
});
