[package]
name = "vaultmesh-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
vaultmesh-sync = { path = "../vault-sync" }
atomic-write-file.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
uuid.workspace = true
vaultmesh-core = { path = "../vault-core" }
zeroize.workspace = true

[dev-dependencies.vaultmesh-sync]
path = "../vault-sync"
features = ["test-hooks"]
